name: AI Daily Digest

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout Repository
      uses: actions/checkout@v3

    - name: 2. Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    # 新增步骤：安装Google Chrome浏览器
    - name: 3. Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: 4. Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 5. Run the Python Script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        SEND_KEY: ${{ secrets.SEND_KEY }}
      run: python main.py
